[package]
name = "rustc_driver"
version = "0.0.0"
edition = "2024"

[lib]
# `lib` is added alongside `dylib` so rustc can be linked statically (required
# when a codegen backend is statically linked in via the off-by-default
# `cranelift` feature). The `dylib` artefact is still produced, so normal builds
# that hot-plug codegen backends are unaffected.
crate-type = ["lib", "dylib"]

[dependencies]
# tidy-alphabetical-start
rustc_driver_impl = { path = "../rustc_driver_impl" }
# tidy-alphabetical-end

[build-dependencies]
# tidy-alphabetical-start
rustc_windows_rc = { path = "../rustc_windows_rc" }
# tidy-alphabetical-end
